"""
Django settings for Musicmate project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '14z%m5%eir51nm-yr+n(pd@^n=%u=(9&lwgu&+@t913e+4!d9x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['your-musicmate.herokuapp.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'main',
    'users',
    'userprofile',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djoser',
    'rest_framework',
    'rest_framework_simplejwt',
    'storages',
    'dropbox',
    'django_dropbox_storage'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Musicmate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Musicmate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

CRISPY_TEMPLATE_PACK = 'bootstrap4'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))#

MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # 'https://dl.dropboxusercontent.com/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')#
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' #
#STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')#

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

#DEFAULT_FILE_STORAGE = 'django_gcloud_storage.DjangoGCloudStorage'


#GCS_PROJECT = os.environ.get('GCS_PROJECT')
#GCS_BUCKET = os.environ.get('GCS_BUCKET')
#GCS_CREDENTIALS_FILE_PATH = os.path.join(BASE_DIR, "my-key.json")
#GCS_USE_UNSIGNED_URLS = True

#AUTH_PROFILE_MODULE = 'base.userprofile'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
#DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN='sl.AnJpYsOY5C6v9woQy_YYA4Iotg8sRl61A_B8ncHOrmX_3n2wOo6LJEIO9tgbtgxaY3Iv3yyAE9yK0yTdXM1eqvAM7S2NPCbpUqgoCjjnYf8TRxhag7mDthrjEVK68DNpwTXHyvo'
DROPBOX_ROOT_PATH='media'

DROPBOX_CONSUMER_KEY = 'hjb2cosepfs7bs2'
DROPBOX_CONSUMER_SECRET ='bwsomx5xaszn50e'
DROPBOX_ACCESS_TOKEN='sl.AnJpYsOY5C6v9woQy_YYA4Iotg8sRl61A_B8ncHOrmX_3n2wOo6LJEIO9tgbtgxaY3Iv3yyAE9yK0yTdXM1eqvAM7S2NPCbpUqgoCjjnYf8TRxhag7mDthrjEVK68DNpwTXHyvo'
