# Generated by Django 3.1.2 on 2020-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201106_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instrument2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
